import { IPalette } from 'styled'

export const mainPalette: IPalette = {
  colorPrimary: '#bf0a45',
  colorSecondary: '#ee7321',
  colorTertiary: '#d4256240',
  colorButtonIntermed: '#e4305d',
  colorTextParagraph: '#757575',
  colorTextTitle: '#222',
  colorTextTitleLarge: '#eee',
  colorTextSubtitleLarge: '#ccc',
  colorTextButton: '#eee',
  colorTextDisabled: '#888',
  colorTextSidebar: '#666',
  colorTextWhite: '#EEE',
  colorBackground: '#f2f2f2',
  colorBackgroundSidebar: '#1a1a1a',
  colorBackgroundDisabled: '#aaa5',
  colorBackgroundBannerEdge: '#505050ff',
  colorBackgroundBannerCenter: '#aaa5',
  colorBackgroundBannerText: '#aaab',
  colorLinkBackground: '#e5e5e5',
  colorLinkBackgroundHover: '#dadada',
  colorImageBackground: '#cccccc',
  colorTrackProgress: '#f43738',
  colorGray: '#999',
  colorWhite: '#FFF',
}
