export enum SPOTIFY_ROUTE {
  OWN = 'me/',
  ALBUMS = 'albums',
  ALBUM = 'albums/:id',
  ALBUM_TRACKS = 'albums/:id/tracks',
  FOLLOWING = 'following',
  FOLLOWING_CHECK = 'following/contains',
  TRACKS = 'tracks',
  PLAYLISTS = 'playlists',
  TOP_ARTISTS = 'top/artists',
  ARTIST = 'artists/:id',
  ARTIST_ALBUMS = 'artists/:id/albums',
  ARTIST_TRACKS = 'artists/:id/top-tracks',
  ARTIST_RELATED = 'artists/:id/related-artists',
  PLAYER = 'player',
  PLAYER_PLAY = 'player/play',
  PLAYER_DEVICES = 'player/devices',
}
