name: test
on: [pull_request]
jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm install
      - run: npm run build
      - run: npx prettier --check .
      - run: npm run lint
      - run: npm test
